config/routes.rb
Blogin::Application.routes.draw do

  get "boom/index"
    
  devise_for :users
  mount Blogit::Engine => "/blog"

  root 'boom#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
  def login_required
  	:authenticate_user!
  end
end

app/controllers/boom_controller.rb
class BoomController < ApplicationController
  def index
       
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boom_helper.rb
module BoomHelper
end

app/views/blogit/comments/_admin_links.html.erb
<%= login_required(class: "actions") do %>
  <%= link_to(t(:delete, scope: 'blogit.comments'), [@post, comment], method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_comment, scope: 'blogit.comments')) %>
<% end %>

app/views/blogit/comments/_comment.html.erb
<%= content_tag(:article, id: "blog_comment_#{comment.id}", class: "blog_comment") do %>
  <%= content_tag(:div, class: "blog_comment_name", id: "blog_comment_#{comment.id}_name") do %>
    <%= comment.website? ? link_to(comment.name, comment.website) : comment.name %>
    <%= t('blogit.comments.wrote') %>
  <% end %>


  <%= content_tag(:div, class: "blog_comment_body",
      id: "blog_comment_#{comment.id}_body") do %>
      <%= format_content comment.body || "" %>
  <% end %>

  <%= blog_tag(:footer, type: "comment") do %>
    <%=t :posted_on, scope: 'blogit.comments'%> 
    <%= time_tag(comment.created_at, format: blogit_conf.datetime_format) %>
  <% end %>

  <%= render partial: "blogit/comments/admin_links", locals: {comment: comment} %>

<% end if comment.persisted? %>

app/views/blogit/comments/_form.html.erb
<%= form_for [post, comment], remote: true,
  html: {
    class: "new_blog_comment", id: "new_blog_comment" } do |f| -%>

  <p><%=t :leave_a_comment, scope: 'blogit.comments'%></p>

  <%= field class: "hidden" do %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
    Hide me using CSS
  <% end %>

  <%= field do %>
    <%= f.label :name, t(:name, scope: 'blogit.comments') %><br>
    <%= f.text_field :name %>
    <%= errors_on(comment, :name) %>
  <% end %>

  <%= field do %>
    <%= f.label :email, t(:email_never_displayed, scope: 'blogit.comments') %><br>
    <%= f.email_field :email %>
    <%= errors_on(comment, :email) %>
  <% end %>

  <%= field do %>
    <%= f.label :website, t(:your_website, scope: 'blogit.comments') %><br>
    <%= f.url_field :website %>
    <%= errors_on(comment, :website) %>
  <% end %>

  <%= field do %>
    <%= f.label :body, t(:your_comment, scope: 'blogit.comments') %><br>
    <%= f.text_area :body %><br>
    <%= errors_on(comment, :body) %>
  <% end %>

  <%= actions do %>
    <%= f.submit t(:add_comment, scope: 'blogit.comments'), :disable_with => t(:adding_comment, scope: 'blogit.comments') %>
  <% end %>
<% end -%>

app/views/blogit/comments/create.js.erb
var $form = $("form#new_blog_comment");
<% if @comment.save %>
  $("#comments").append("<%= escape_javascript(render(@comment)) %>");
  $form.get(0).reset();
<% else %>
  $form.html("<%= escape_javascript(render(partial:'form', locals: { post: @comment.post, comment: @comment })) %>");
<% end %>

app/views/blogit/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blog_post_spacer">

app/views/blogit/posts/_blogger_information.html.erb
<%= blog_tag :footer do %>
    <%=t :written_by, scope: 'blogit.posts', author: "'" + post.blogger_display_name + "'"%>
    <span class="bTimeStamp"><%= time_tag(post.created_at, pubdate: true, format: blogit_conf.datetime_format) %></span>
<% end %>

app/views/blogit/posts/_comments_count.html.erb
<%= content_tag(:div, class: "blog_post_comments_count", id: "blog_post_#{post.id}_comments_count") do %>
  <%= link_to(post_path(post, anchor: "comments")) do %>
    <%=t :comment, scope: 'blogit.posts', count: post.comments_count %>
  <% end %>
<% end %>

app/views/blogit/posts/_disqus_comments.html.erb
<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'ramukaka'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message alert alert-danger">
  Oops!! Looks like there are no posts yet.
</div>

app/views/blogit/posts/_form.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2 class=" alert alert-danger"><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul class=" alert alert-danger bErrorList">
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= field do %>
      <%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts'), :class=>"form-control bNewPostTitle" %>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts'),:class=>"wysihtml5 form-control bRichText",:id=>"some-textarea" %>

    <script type="text/javascript">
      $(document).ready(function(){
        $('.wysihtml5').each(function(i, elem) {
          $(elem).wysihtml5();
        });
      })
    </script>
    <% end %> 

  </fieldset>

  <fieldset>

    <%= field id: "new_blog_post_tag_field", :class=>"bOptions bOptionsTag pull-left hidden" do %>
      <%= f.label :tag_list, t(:tags, scope: 'blogit.posts') %>
      <%= f.text_field :tag_list, :class=>"form-control bTag", placeholder: t(:tag_placeholder, scope: 'blogit.posts') %>
    <% end %>

    <%= field id: "new_blog_post_state_field", :class=> "bOptions" do %>
      <%= f.label :state, t(:state, scope: 'blogit.posts') %>
      <%= f.collection_select :state, Blogit::Post::AVAILABLE_STATUS, :to_s, :to_s,{:class=>"form-control bTag pull-right"} %>
    <% end %>
  </fieldset>
<p class="blog_post_tip label label-info">
      <%=t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>

  <%= actions do %>
        <%= f.submit "Create Post", :class=>"btn btn-success"%>
    <%= link_to(t(:Cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post), :class=>"btn btn-danger") %>
  <% end %>

<% end %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post.html.erb
<%= content_tag(:article, id: "blog_post_#{post.id}", class: "blog_post") do %>

  <%# Render the header for this blog post %>
  <%= render "blogit/posts/post_head", post: post %>
  <hr>
  <%# Render the body of this blog post (as Markdown) %>
  <%= render "blogit/posts/post_body", post: post %>
  <hr>
  <%# Render admin links to edit/delete this post %>
  <%= render "blogit/posts/post_links", post: post %>

  <%# Render info about the person who wrote this post %>
  <%= render "blogit/posts/blogger_information", post: post %>

  <%# Render the no. of comments %>
  <%= render "blogit/posts/comments_count",
    post: post if defined?(show_comments_count) and show_comments_count %>

<% end %>

app/views/blogit/posts/_post_links.html.erb
<%= login_required do  %>
  <%= actions do %>
  	<% if (post.blogger_id== current_user.id) %>
    		<%= link_to(t(:Edit, scope: 'blogit.posts'), edit_post_path(post),  :class =>"btn btn-primary btn-xs") %>  <%= link_to(t(:Delete, scope: 'blogit.posts'), post, method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_post, scope: 'blogit.posts'), :class =>"btn btn-danger btn-xs") %>
  	<% end %>  
  <% end %>
<% end unless blogit_conf.author_edits_only and not this_blogger?(post) %>
<br>

app/views/blogit/posts/_share_bar.html.erb
<div id="blog_share_bar">
  <div id="google-plus" class="social_button pull-left">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div id="twitter" class="social_button pull-left">
    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div id="facebook" class="social_button pull-left">
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>
</div>

app/views/blogit/posts/edit.html.erb
<h2><%=t :edit_blog_post, scope: 'blogit.posts', id: @post.id %></h2>

<%= render 'form' %>

app/views/blogit/posts/new.html.erb
<div class="bCreatePost">
<h2 class="bNew"><span class="glyphicon glyphicon-file"></span> <%=t :write_a_new_blog_post, scope: 'blogit.posts'%></h2>

<hr>
 
<%= render 'form' %>
</div>

app/views/blogit/posts/show.html.erb
<%= render @post %>
<%= share_bar_for @post %>
<%= render "blogit/posts/post_footer", post: @post %>
<%= comments_for @post %>

app/views/boom/index.html.erb
<div class="jumbotron bLanding">
  <div class="container">
    <h1>BLOG<span class="glyphicon glyphicon-pencil"></span>N</h1>
    <h3>Your own personal blogging engine to write blogs.</h3>
    <br>
    <%= link_to "<span class='glyphicon glyphicon-fire'></span>".html_safe + ' Fire it up', '/blog', :class =>"btn btn-lg btn-primary btnFire"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogin</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
            <%= link_to "BlogIn","/", :class=>"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Blogs', '/blog'%></li>
        <li><% if user_signed_in? %>
            <%= link_to "<button class='btn btn-xs btn-success navbar-btn'><span class='glyphicon glyphicon-plu-sign'></span>New Blog Post</button>".html_safe, "/blog/posts/new" %>
            <% end %></li>
    </ul>
      
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
        <li><p class="navbar-text">Signed in as <span class="bUser"><%= current_user.email %></span></p></li>
        <li><%= link_to "<button class='btn btn-xs btn-danger navbar-btn btnNav'>Sign Out</button>".html_safe, "/users/sign_out" ,method: :delete %></li>
    <% else %>
        <li><%= link_to "<button class='btn btn-xs btn-info navbar-btn btnNav'>Register</button>".html_safe, "/users/sign_up" %></li>
        <li><%= link_to "<button class='btn btn-xs btn-success navbar-btn btnNav'>Sign In</button>".html_safe, "/users/sign_in" %></li>
    <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="Mid">
	<%= yield %>
</div>
</body>
</html>